import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    include: ["tests/**/*.test.{ts,tsx}"],
    setupFiles: ["./tests/setup.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      reportsDirectory: "../../coverage/web",
      include: [
        "src/app/app-navigation-guard.ts",
        "src/cache/financial-query-keys.ts",
        "src/components/ui/ActionButton.tsx",
        "src/components/ui/FeedbackConfirmation.tsx",
        "src/components/ui/SkeletonBlock.tsx",
        "src/dates/**/*.ts",
        "src/money/**/*.ts",
        "src/features/auth/clipboard.ts",
        "src/features/auth/desktop-legal-path.ts",
        "src/features/auth/email-validation.ts",
        "src/features/auth/login-identifier-validation.ts",
        "src/features/auth/password-assistance.ts",
        "src/features/auth/password-validation.ts",
        "src/features/auth/registration-validation.ts",
        "src/features/auth/username-validation.ts",
        "src/features/auth/user-name-validation.ts",
        "src/features/home/feedback-api.ts",
        "src/features/home/home-api.ts",
        "src/features/onboarding/starting-net-worth-api.ts",
        "src/features/statistics/statistics-api.ts",
        "src/features/statistics/statistics-categories.ts",
        "src/features/statistics/statistics-category-switch.ts",
        "src/features/statistics/charts/statistics-chart-periods.ts",
        "src/features/transactions/category-catalog.ts",
        "src/features/transactions/moves-filter-summary.ts",
        "src/features/transactions/moves-filters.ts",
        "src/features/transactions/transaction-api.ts",
        "src/features/transactions/transaction-share.ts",
        "src/features/transactions/transaction-validation.ts",
      ],
      thresholds: {
        statements: 80,
        branches: 70,
        functions: 85,
        lines: 80,
      },
    },
  },
});
